version: '3'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: dockerfile
    image: time_checker2_test_nginx
    container_name: nginx-container
    stdin_open: true
    volumes:
      - ./docker/nginx/html:/usr/share/nginx/html
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    ports:
      - 3000:80



networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24